---
###############################################################
#                   Authelia configuration                    #
###############################################################

jwt_secret: a_very_important_secret
default_redirection_url: https://dev.example.com

server:
  host: 0.0.0.0
  port: 9091

log:
  level: debug

totp:
  issuer: authelia.com

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: deny
  rules:
#####
    - domain: dev.example.com
      policy: bypass
#####
    - domain: traefik.dev.example.com
      policy: one_factor
      subject: "group:admins"
    - domain: tool1.group1.dev.example.com
      policy: one_factor
      subject: "group:group1"
    - domain: rapid.group2.dev.example.com
      policy: one_factor
      subject: "group:group2"
#####
    - domain: tool2.group1.dev.example.com
      policy: one_factor
      subject: "group:group1"
    - domain: mineit.group2.dev.example.com
      policy: one_factor
      subject: 'group:myhome'

session:
  secret: unsecure_session_secret
  domain: dev.example.com  # Should match whatever your root protected domain is

  # cookies:
  #   - name: authelia_session
  #     expiration: 3600  # 1 hour
  #     inactivity: 300  # 5 minutes

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  encryption_key: you_must_generate_a_random_string_of_more_than_twenty_chars_and_configure_this
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt
...
